# fly.toml app configuration file generated for google2ai on 2026-09-20T00:51:54Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'google2ai'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  GSC_TZ = 'Europe/Ljubljana'
  LOG_LEVEL = 'info'
  PORT = '8000'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
